name: splinegen
channels:
  - lambouj
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.10.9
  - matplotlib==3.7.0
  - numpy
  - pybind11==2.11.1
  - scikit-learn==1.2.1
  - scipy==1.10.1
  - setuptools=65.6.3
  - pytorch==2.0.1
  - tqdm==4.62.3
  - torchvision==0.15.2
  - pytorch-cuda=11.8
  - pythonocc-core=7.8.1
  - tensorboard
